<a href="https://colab.research.google.com/github/bharaniakella/Akellian_DL/blob/main/ann_Parameters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import torch.nn as nn

In [4]:
deep_net=nn.Sequential(
    nn.Linear(2,2),
    nn.ReLU(),
    nn.Linear(2,2),
    nn.ReLU(),
    nn.Linear(2,1)
)

wide_net = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

In [6]:
for p in deep_net.named_parameters():
  print(p)

('0.weight', Parameter containing:
tensor([[-0.5288,  0.1587],
        [ 0.5909,  0.1821]], requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.5054, -0.6755], requires_grad=True))
('2.weight', Parameter containing:
tensor([[-0.5778, -0.4300],
        [-0.4464, -0.0039]], requires_grad=True))
('2.bias', Parameter containing:
tensor([0.3858, 0.5968], requires_grad=True))
('4.weight', Parameter containing:
tensor([[-0.6490,  0.4621]], requires_grad=True))
('4.bias', Parameter containing:
tensor([-0.0492], requires_grad=True))


In [7]:
for p in wide_net.named_parameters():
  print(p)

('0.weight', Parameter containing:
tensor([[-0.1526, -0.1443],
        [-0.4140,  0.6749],
        [ 0.0368,  0.3269],
        [-0.0459,  0.3144]], requires_grad=True))
('0.bias', Parameter containing:
tensor([-0.6127, -0.5270, -0.3026, -0.0058], requires_grad=True))
('2.weight', Parameter containing:
tensor([[ 0.2687, -0.3341,  0.3506,  0.4322]], requires_grad=True))
('2.bias', Parameter containing:
tensor([-0.0126], requires_grad=True))


In [14]:
total_nodes=0
for p in deep_net.named_parameters():
  if 'bias' in p[0]:
    total_nodes=total_nodes+len(p[1])

total_nodes

5

In [13]:
total_nodes=0
for p in wide_net.named_parameters():
  if 'bias' in p[0]:
    total_nodes=total_nodes+len(p[1])

total_nodes

5

In [12]:
for parameter_name,parameter_value in deep_net.named_parameters():
  print(parameter_value)

Parameter containing:
tensor([[-0.5288,  0.1587],
        [ 0.5909,  0.1821]], requires_grad=True)
Parameter containing:
tensor([-0.5054, -0.6755], requires_grad=True)
Parameter containing:
tensor([[-0.5778, -0.4300],
        [-0.4464, -0.0039]], requires_grad=True)
Parameter containing:
tensor([0.3858, 0.5968], requires_grad=True)
Parameter containing:
tensor([[-0.6490,  0.4621]], requires_grad=True)
Parameter containing:
tensor([-0.0492], requires_grad=True)


In [16]:
num_train=0
for p in deep_net.parameters():
  if p.requires_grad:
    num_train=num_train+p.numel()
num_train

15

In [19]:
from torchsummary import summary
summary(wide_net,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
              ReLU-2                 [-1, 1, 4]               0
            Linear-3                 [-1, 1, 1]               5
Total params: 17
Trainable params: 17
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [20]:
from torchsummary import summary
summary(deep_net,(1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 2]               6
              ReLU-2                 [-1, 1, 2]               0
            Linear-3                 [-1, 1, 2]               6
              ReLU-4                 [-1, 1, 2]               0
            Linear-5                 [-1, 1, 1]               3
Total params: 15
Trainable params: 15
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
