<a href="https://colab.research.google.com/github/bharaniakella/Akellian_DL/blob/main/drop_out_layer_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [38]:
prob=0.5
x=torch.ones(10)
dropout=nn.Dropout(p=prob)
print(x)
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 2., 2., 2., 0., 0., 0., 2., 2.])
tensor(1.2000)


In [39]:
prob=0.5
x=torch.ones(10)
dropout=nn.Dropout(p=prob)
print(x)
y=dropout(x*(1-prob))
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 0., 1., 1., 0., 0., 0., 0., 0., 0.])
tensor(0.3000)


In [40]:
prob=0.5
x=torch.ones(10)
dropout=nn.Dropout(p=prob)
dropout.train()
print(x)
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 0., 2., 2., 2., 2., 0., 0., 0., 0.])
tensor(0.8000)


In [41]:
prob=0.5
x=torch.ones(10)
dropout=nn.Dropout(p=prob)
dropout.train()
print(x)
dropout.eval()
y=dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [44]:
dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 0., 0., 2., 0., 2., 0., 0., 0., 0.])
tensor(0.6000)


In [47]:
dropout.eval()
y = F.dropout(x,training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)
